"""Add serve_points to tennis_match_stats

Revision ID: 1335809ab3f6
Revises: 4dd762c3cef7
Create Date: 2026-06-02 01:41:37.011531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1335809ab3f6'
down_revision: Union[str, Sequence[str], None] = '4dd762c3cef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tennis_match_stats', sa.Column('serve_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tennis_match_stats', 'serve_points')
    # ### end Alembic commands ###
