"""add bet_slips and bet_slip_legs

Revision ID: 5b056655411e
Revises: 5f51f0559771
Create Date: 2026-06-02 23:08:11.839360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b056655411e'
down_revision: Union[str, Sequence[str], None] = '5f51f0559771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_slips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('combined_odd', sa.Float(), nullable=True),
    sa.Column('ev', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reject_reason', sa.String(length=60), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('model_version', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_slips_status'), 'bet_slips', ['status'], unique=False)
    op.create_table('bet_slip_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slip_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('bookmaker_id', sa.Integer(), nullable=True),
    sa.Column('selection', sa.String(length=40), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('odd', sa.Float(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['slip_id'], ['bet_slips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_slip_legs_slip_id'), 'bet_slip_legs', ['slip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bet_slip_legs_slip_id'), table_name='bet_slip_legs')
    op.drop_table('bet_slip_legs')
    op.drop_index(op.f('ix_bet_slips_status'), table_name='bet_slips')
    op.drop_table('bet_slips')
    # ### end Alembic commands ###
