"""add odds_ingest_raw staging

Revision ID: 5f51f0559771
Revises: e9a5e1ec1c7c
Create Date: 2026-06-02 22:40:06.536815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f51f0559771'
down_revision: Union[str, Sequence[str], None] = 'e9a5e1ec1c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odds_ingest_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=80), nullable=True),
    sa.Column('screenshot_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('bookmaker', sa.String(length=80), nullable=False),
    sa.Column('home_raw', sa.String(length=120), nullable=True),
    sa.Column('away_raw', sa.String(length=120), nullable=True),
    sa.Column('league', sa.String(length=50), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('market', sa.String(length=40), nullable=False),
    sa.Column('selection', sa.String(length=40), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('odd', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('kickoff', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reject_reason', sa.String(length=60), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('promoted_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['promoted_snapshot_id'], ['odds_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_ingest_raw_batch_id'), 'odds_ingest_raw', ['batch_id'], unique=False)
    op.create_index(op.f('ix_odds_ingest_raw_status'), 'odds_ingest_raw', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odds_ingest_raw_status'), table_name='odds_ingest_raw')
    op.drop_index(op.f('ix_odds_ingest_raw_batch_id'), table_name='odds_ingest_raw')
    op.drop_table('odds_ingest_raw')
    # ### end Alembic commands ###
