"""add prematch feature store

Revision ID: 6753adf773bb
Revises: e778e08d0cab
Create Date: 2026-06-02 18:51:20.580193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6753adf773bb'
down_revision: Union[str, Sequence[str], None] = 'e778e08d0cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prematch_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('feature_set_version', sa.String(length=40), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=True),
    sa.Column('window', sa.Integer(), nullable=True),
    sa.Column('home_form', sa.Float(), nullable=True),
    sa.Column('away_form', sa.Float(), nullable=True),
    sa.Column('home_xgf', sa.Float(), nullable=True),
    sa.Column('home_xga', sa.Float(), nullable=True),
    sa.Column('away_xgf', sa.Float(), nullable=True),
    sa.Column('away_xga', sa.Float(), nullable=True),
    sa.Column('home_rest_days', sa.Integer(), nullable=True),
    sa.Column('away_rest_days', sa.Integer(), nullable=True),
    sa.Column('home_hist_n', sa.Integer(), nullable=True),
    sa.Column('away_hist_n', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'feature_set_version', name='uq_prematch_feature')
    )
    op.create_index(op.f('ix_prematch_features_match_id'), 'prematch_features', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prematch_features_match_id'), table_name='prematch_features')
    op.drop_table('prematch_features')
    # ### end Alembic commands ###
