"""add bet_decisions audit

Revision ID: 7b90a821d1a0
Revises: 4f00ac688cd3
Create Date: 2026-06-02 19:06:02.875792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b90a821d1a0'
down_revision: Union[str, Sequence[str], None] = '4f00ac688cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_label', sa.String(length=80), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('selection', sa.String(length=40), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('model_version', sa.String(length=40), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('odd', sa.Float(), nullable=True),
    sa.Column('ev', sa.Float(), nullable=True),
    sa.Column('decided', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_decisions_match_id'), 'bet_decisions', ['match_id'], unique=False)
    op.create_index(op.f('ix_bet_decisions_run_label'), 'bet_decisions', ['run_label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bet_decisions_run_label'), table_name='bet_decisions')
    op.drop_index(op.f('ix_bet_decisions_match_id'), table_name='bet_decisions')
    op.drop_table('bet_decisions')
    # ### end Alembic commands ###
