"""add betting data layer

Revision ID: e778e08d0cab
Revises: faf1194f82bf
Create Date: 2026-06-02 18:36:52.956938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e778e08d0cab'
down_revision: Union[str, Sequence[str], None] = 'faf1194f82bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('is_exchange', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('current_odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('selection', sa.String(length=40), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('odd', sa.Float(), nullable=False),
    sa.Column('implied_prob', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'bookmaker_id', 'market_id', 'selection', 'line', name='uq_current_odds')
    )
    op.create_index(op.f('ix_current_odds_match_id'), 'current_odds', ['match_id'], unique=False)
    op.create_table('market_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('selection', sa.String(length=40), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('result_value', sa.Float(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'market_id', 'selection', 'line', name='uq_market_result')
    )
    op.create_index(op.f('ix_market_results_match_id'), 'market_results', ['match_id'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('selection', sa.String(length=40), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('odd', sa.Float(), nullable=False),
    sa.Column('implied_prob', sa.Float(), nullable=True),
    sa.Column('is_opening', sa.Boolean(), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_odds_snap_match_market_sel_time', 'odds_snapshots', ['match_id', 'market_id', 'selection', 'captured_at'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_captured_at'), 'odds_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_match_id'), 'odds_snapshots', ['match_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('selection', sa.String(length=40), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('fair_odd', sa.Float(), nullable=True),
    sa.Column('edge', sa.Float(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'model_name', 'model_version', 'market_id', 'selection', 'line', name='uq_prediction')
    )
    op.create_index(op.f('ix_predictions_match_id'), 'predictions', ['match_id'], unique=False)
    op.create_table('simulated_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('selection', sa.String(length=40), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('odd_taken', sa.Float(), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('model_version', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulated_bets_match_id'), 'simulated_bets', ['match_id'], unique=False)
    op.create_table('bankroll_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['simulated_bets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bankroll_transactions_ts'), 'bankroll_transactions', ['ts'], unique=False)
    op.add_column('data_sources', sa.Column('reliability', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'reliability')
    op.drop_index(op.f('ix_bankroll_transactions_ts'), table_name='bankroll_transactions')
    op.drop_table('bankroll_transactions')
    op.drop_index(op.f('ix_simulated_bets_match_id'), table_name='simulated_bets')
    op.drop_table('simulated_bets')
    op.drop_index(op.f('ix_predictions_match_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_odds_snapshots_match_id'), table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_captured_at'), table_name='odds_snapshots')
    op.drop_index('ix_odds_snap_match_market_sel_time', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index(op.f('ix_market_results_match_id'), table_name='market_results')
    op.drop_table('market_results')
    op.drop_index(op.f('ix_current_odds_match_id'), table_name='current_odds')
    op.drop_table('current_odds')
    op.drop_table('markets')
    op.drop_table('bookmakers')
    # ### end Alembic commands ###
