"""add match context, fundamentals, team-match stat columns

Revision ID: e9a5e1ec1c7c
Revises: 7b90a821d1a0
Create Date: 2026-06-02 19:09:40.840671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a5e1ec1c7c'
down_revision: Union[str, Sequence[str], None] = '7b90a821d1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamental_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_quality', sa.String(length=20), nullable=True),
    sa.Column('as_of', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', 'kind', name='uq_fundamental_note')
    )
    op.create_index(op.f('ix_fundamental_notes_match_id'), 'fundamental_notes', ['match_id'], unique=False)
    op.create_index(op.f('ix_fundamental_notes_team_id'), 'fundamental_notes', ['team_id'], unique=False)
    op.create_table('match_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('referee', sa.String(length=120), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('importance', sa.String(length=40), nullable=True),
    sa.Column('weather', sa.JSON(), nullable=True),
    sa.Column('travel_km_home', sa.Float(), nullable=True),
    sa.Column('travel_km_away', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', name='uq_match_context_match')
    )
    op.create_index(op.f('ix_match_context_match_id'), 'match_context', ['match_id'], unique=False)
    op.add_column('match_team_stats', sa.Column('shots_total', sa.Integer(), nullable=True))
    op.add_column('match_team_stats', sa.Column('shots_on_target', sa.Integer(), nullable=True))
    op.add_column('match_team_stats', sa.Column('corners', sa.Integer(), nullable=True))
    op.add_column('match_team_stats', sa.Column('yellow_cards', sa.Integer(), nullable=True))
    op.add_column('match_team_stats', sa.Column('red_cards', sa.Integer(), nullable=True))
    op.add_column('match_team_stats', sa.Column('possession', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_team_stats', 'possession')
    op.drop_column('match_team_stats', 'red_cards')
    op.drop_column('match_team_stats', 'yellow_cards')
    op.drop_column('match_team_stats', 'corners')
    op.drop_column('match_team_stats', 'shots_on_target')
    op.drop_column('match_team_stats', 'shots_total')
    op.drop_index(op.f('ix_match_context_match_id'), table_name='match_context')
    op.drop_table('match_context')
    op.drop_index(op.f('ix_fundamental_notes_team_id'), table_name='fundamental_notes')
    op.drop_index(op.f('ix_fundamental_notes_match_id'), table_name='fundamental_notes')
    op.drop_table('fundamental_notes')
    # ### end Alembic commands ###
